Личный проект: вдохнуть жизнь
htmlacademy-nodejs/427583-typoteka-3 pull request #12
Opened 2021-06-10 20:00 UTC by RomanBykov

---
:mortar_board: [Личный проект: вдохнуть жизнь](https://up.htmlacademy.ru/nodejs/3/user/427583/tasks/25)

2021-06-11 15:21 UTC, Krabaton requested changes

2021-06-11 15:21 UTC, Krabaton commented on src/express/templates/articles/edit-post.pug
> +          form(action='/articles' method='PUT')
Формы поддерживают только POST и GET [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form#attr-method)

2021-06-11 15:21 UTC, Krabaton commented on src/express/templates/errors/404.pug
> +    script(src='../js/vendor.js')
Надо использовать абсолютные пути, а не относительные

2021-06-12 17:25 UTC, RomanBykov commented on src/express/templates/articles/edit-post.pug
> +          form(action='/articles' method='PUT')
Ой, точно. Спасибо большое

2021-06-12 17:26 UTC, RomanBykov commented on src/express/templates/errors/404.pug
> +    script(src='../js/vendor.js')
Спасибо, исправил

2021-06-14 23:56 UTC, merged